### ISSUE TITLE
Add more regex patterns

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/expynent#1]
It would be great to add more regular expression patterns or improve existing patterns.

**Comment by the-zebulan** [comment]
@lk-geimfari ,

Added a regex for Canadian postal codes (our zip codes), #6

**Comment by lk-geimfari** [comment]
@the-zebulan Thanks!

**Comment by the-zebulan** [comment]
@lk-geimfari ,

No problem!

**Comment by shanmbic** [comment]
Added regex to match html tags with html events attached !
PR : https://github.com/lk-geimfari/expynent/pull/19

**Comment by Kurolox** [comment]
Added regex for spanish phone numbers and IRC usernames. #23

**Comment by TroyCode** [comment]
Added regex for license plates from Taiwan!
#32
