### ISSUE TITLE
Email regex is invalid

### ISSUE THREAD

**Issue by sametmax** [lk-geimfari/expynent#12]
I sampled a view exotic email addresses that are allowed by the RFC:
```
In [3]: exotic_addresses = ['"Abc\@def"@example.com',
   ...: '"Fred Bloggs"@example.com',
   ...: '"Joe\\Blow"@example.com',
   ...: '"Abc@def"@example.com',
   ...: 'customer/department=shipping@example.com',
   ...: '$A12345@example.com',
   ...: '!def!xyz%abc@example.com',
   ...: '_somename@example.com']
   ...: 
   ...: for email in exotic_addresses:
   ...:     print(email, 
   ...:           bool(re.match(r'^(\w+([-+.]\w+)*)\w*@(\w+([-.]\w+)*\.\w+([-.]\w+)*)$', 
   ...:                email))
   ...: 
   ...:     
   ...:     
   ...:     
   ...:     )
   ...:     
"Abc\@def"@example.com False
"Fred Bloggs"@example.com False
"Joe\Blow"@example.com False
"Abc@def"@example.com False
customer/department=shipping@example.com False
$A12345@example.com False
!def!xyz%abc@example.com False
_somename@example.com True
```

The regex reject most of them.

Here is the official fully valid regex:

http://www.ex-parrot.com/~pdw/Mail-RFC822-Address.html

As you can see, regex are just not pratical to validate email and one should not use them. There are 2 wise more for email validation:

- check you have @ in the email, and warn the user if it's not the case.
- send an email to the address and ask the user to click a confirmation link.

Anything other than that will eventually block some legitimate addresses.

**Comment by lk-geimfari** [comment]
@sametmax I hope that we fix it. If you have free time then you can sen us you PR.

**Comment by the-zebulan** [comment]
@lk-geimfari ,

It seems @sametmax is saying it's better not to use regex for email.

 Do you think it should be deleted?

**Comment by lk-geimfari** [comment]
@the-zebulan I think that yes. If it's don't worked then we need better solution for matching email address.
