### ISSUE TITLE
HTML tag regex fails

### ISSUE THREAD

**Issue by sametmax** [lk-geimfari/expynent#14]
HTML is not a regular language, and can not be cleanly parsed using regular expression. One should not promote it, and it should be removed.

Real life HTML indeed contains many corner cases such as mixing css and js in the same code, and comments:
```
<style>
   .foo > .bar {
      color: red;
   }
</style>
</head>
<body>
  <!--Was <br clear="all"> <a>... -->   
  <script type="text/javascript"> 
 // <![CDATA[
     if (width > height) {
        $('<p></p>').append('body')
     }
  // ]]>
  </script> <hr />
<button onclick='console.log("You should go >>> [] <<<")'>Click</button>
</body>

```

**Comment by lk-geimfari** [comment]
@sametmax We removed this regex, because regex for HTML it's not better idea.
