### ISSUE TITLE
Provide regexes in text format then python wrapper

### ISSUE THREAD

**Issue by sametmax** [lk-geimfari/expynent#15]
If you provide the regexes in a language agnostic format, pure text, json, .ini, whatever, you'll allow more people to benefit from it or contribute to it. You can then just provide a Python wrapper loading the reggexes. This would also allow you to have multilingual descriptions matching each regexxes.

**Comment by the-zebulan** [comment]
@sametmax ,

This seems like a good idea.

**Comment by lk-geimfari** [comment]
@sametmax I think that is good idea and i hope that we can do it. Now `expynent` is only experimental project and we fix it in version 1.0.0

**Comment by lk-geimfari** [comment]
@the-zebulan Can you give me your email? A want to add you to collaborators.

**Comment by lk-geimfari** [comment]
@the-zebulan If you are interested in the project, together we can make something worthwhile.

**Comment by lk-geimfari** [comment]
@the-zebulan I send you invitation. Now, you're collaborator.

**Comment by the-zebulan** [comment]
@lk-geimfari ,

Thanks for the invitation! It's an interesting idea, I have a few ideas in mind.

**Comment by lk-geimfari** [comment]
@the-zebulan Nice!

**Comment by lk-geimfari** [comment]
@the-zebulan If you are from Canada, I can offer you also take part in [another project](https://github.com/lk-geimfari/church), where we really need to add support for Canadian data.
