### ISSUE TITLE
Recommendation form the reddit

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/expynent#21]
[Some people ](https://www.reddit.com/r/Python/comments/58pke0/expynent_is_a_library_that_provides_regex/)offer a very interesting and important recommendations, and I think we should consider all recommendations and make good decisions.

**Comment by the-zebulan** [comment]
https://www.reddit.com/r/Python/comments/58pke0/expynent_is_a_library_that_provides_regex/

It's an interesting discussion and they make some good points. They are correct in saying regexes are not the best solution for a lot of problems.

One of the regexes I'm not a big fan of is the password regex. Almost every website has a different character set (eg. [a-z0-9] or [a-zA-Z0-9_] or [a-zA-Z], etc) and different rules about minimum and maximum lengths. A one-size-fits-all regex doesn't seem to exist.

When a pattern is somewhat complex and fixed (or almost always the same), that might work for a regex. But checking for simple things like is '12345' all digits and 5 digits long can be quite simple using other methods (`if '12345'.isdigit() and len('12345') == 5`).

**Comment by lk-geimfari** [comment]
@the-zebulan I think that we need to remove all bad solutions and leave only good decisions. So, i hear that regex for HTML also is bad idea. What do you think about it? Can we remove bad solutions?

**Comment by the-zebulan** [comment]
@lk-geimfari ,

I think that's a good idea. How about I start by removing these?

* HTML
* domain
* dates/years
* password

**Comment by the-zebulan** [comment]
I removed those and the associated tests. I'm working on updating the MAC address regex and tests right now.

**Comment by lk-geimfari** [comment]
@the-zebulan Excellent!

**Comment by kdeldycke** [comment]
You might find a couple of counter-examples at: https://github.com/kdeldycke/awesome-falsehood

**Comment by lk-geimfari** [comment]
@kdeldycke Thank you!
