### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by kimond** [lk-geimfari/expynent#33]
Did you write the documentation somewhere?

**Comment by lk-geimfari** [comment]
@kimond At this moment we don't have documentation, but I'll try to fix it.

**Comment by sagvin** [comment]
@lk-geimfari  hey pal, I have a little knowledge about python and regular expressions and I would love to provide documentation? where do think I should start? What should be the contents.

**Comment by lk-geimfari** [comment]
@sagvin Actually `expynent` is very small tool. And all that you need is quick look at code.

If you want help us write docs, then [here](https://github.com/lk-geimfari/expynent/wiki) you can find example for some features.

**Comment by sagvin** [comment]
@lk-geimfari Are there any new features you would like to develop and need help on, I am new here and I am a bit confident that I could work on this? can you please tell me if you have any features in mind so I can work on them.,

**Comment by lk-geimfari** [comment]
@sagvin Actually we have some issues with regex for IPv6. You can find out what is the problem?

**Comment by lk-geimfari** [comment]
@sagvin Also you can add new features if you have some ideas.

**Comment by sagvin** [comment]
@lk-geimfari  I think I will look at the issue with regex fro IPv6 as soon as I can

**Comment by lk-geimfari** [comment]
@sagvin Okay. Thank you!
