### ISSUE TITLE
IPv4 pattern is too general

### ISSUE THREAD

**Issue by Eckankar** [lk-geimfari/expynent#43]
The IPv4 pattern matches invalid values such as 999.999.999.999.

The test suite for that pattern should also be expanded, to test against some known good, and some known bad values that might trip it up.

**Comment by lk-geimfari** [comment]
@Eckankar Thank you. I'll work on it as soon as possible.

**Comment by oleg104** [comment]
@lk-geimfari, I think you can close this issue. It was fixed by #44 and #45

**Comment by lk-geimfari** [comment]
@oleg104 Oh, of course. I completely forgot about it. Thank you for reminding me.
