### ISSUE TITLE
Generate sphinx documentation.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/expynent#54]
We need the documentation. I suggest using [Sphinx](http://www.sphinx-doc.org/en/stable/).

**Comment by aswinmohanme** [comment]
I will start working on this right away ! Happy Hacktoberfest

**Comment by lk-geimfari** [comment]
@aswinmohanme Thank you! You are assigned.

**Comment by lk-geimfari** [comment]
@aswinmohanme I recommend you take a look at our wiki too: https://github.com/lk-geimfari/expynent/wiki

We need similar structure for our documentation.

**Comment by aswinmohanme** [comment]
Alright, And pretty neat library too

**Comment by nioperas06** [comment]
Hi! Can I help too? 😅

**Comment by lk-geimfari** [comment]
@nioperas06 Of course! You can join to @aswinmohanme and work on branch together. Thanks!

**Comment by aswinmohanme** [comment]
It seems that most of the code is are regular expressions (obviously). So what should be included in the documentation.

**Comment by lk-geimfari** [comment]
@aswinmohanme We need to describe all regular expressions with examples.

**Comment by aswinmohanme** [comment]
So that means there is no need of autodocs, and we have to describe everything by hand then .

**Comment by lk-geimfari** [comment]
@aswinmohanme Right. Just describe regex with good example.
